version: '3.8'

services:
  # الحاوية الأولى: الخاصة بمعالجة البيانات بـ Spark
  ecowater_spark_processor:
    build: .
    container_name: ecowater_spark_container
    volumes:
      - ./data:/app/data
      - ./global_data:/app/global_data
    environment:
      - DB_SERVER=sql_server_host
      - DB_NAME=Global_And_Egypt_Warehouse_DB
    ports:
      - "4040:4040"
    networks:
      - ecowater_pipeline_network
    restart: on-failure

  # الحاوية الثانية: الخاصة بأتمتة وجدولة الخطوات بـ Airflow
  airflow_orchestrator:
    image: apache/airflow:2.5.1-python3.9
    container_name: ecowater_airflow_container
    volumes:
      - .:/opt/airflow/dags
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    networks:
      - ecowater_pipeline_network
    restart: always

networks:
  ecowater_pipeline_network:
    driver: bridge